import { UserFinancialProfile } from "./types";

export const SAMPLE_PROFILES: { [key: string]: { label: string; description: string; data: UserFinancialProfile } } = {
  fresh_grad: {
    label: "🌱 First-Jobber / Fresh Grad (Age 24)",
    description: "Planning S$3,000/mo today-dollar retirement, Wedding in 2 yrs, BTO in 4 yrs, and student loan payoff.",
    data: {
      id: "profile-fresh-grad",
      name: "Alex Lee",
      currentAge: 24,
      targetRetirementAge: 58,
      lifeExpectancy: 88, // 30 years in retirement (Age 58 to 88)
      desiredMonthlyRetirementSpendToday: 3000, // S$3,000/mo in today's purchasing power
      retirementLifestylePreset: "comfortable",
      maritalStatus: "single",
      employmentType: "employed",
      riskProfile: "growth",
      currency: "SGD",
      planningCadence: "monthly",
      planningScope: "individual",
      planningStartMonthYear: "2026-06",
      activePlanningMonthYear: "2026-08",
      monthlyLogs: [
        {
          id: "log-2026-06",
          monthYear: "2026-06",
          monthLabel: "June 2026",
          dateRecorded: "2026-06-30",
          totalIncome: 4200,
          totalExpenses: 2820,
          totalDcaInvested: 150,
          netSavings: 1230,
          savingsRatePercentage: 29.3,
          netWorthAtMonthEnd: 7800,
          keyNotes: "First month starting the financial needs plan! Cleared $300 tuition loan principal.",
        },
        {
          id: "log-2026-07",
          monthYear: "2026-07",
          monthLabel: "July 2026",
          dateRecorded: "2026-07-31",
          totalIncome: 4200,
          totalExpenses: 2750,
          totalDcaInvested: 200,
          netSavings: 1250,
          savingsRatePercentage: 29.8,
          netWorthAtMonthEnd: 9250,
          keyNotes: "Reduced food delivery leak by cooking 3x a week. Auto-DCA increased to $200.",
        },
      ],
      cpfLife: {
        isEnabled: true,
        planTier: "full_frs",
        estimatedMonthlyPayoutToday: 1650,
        payoutStartAge: 65,
      },
      yearlySnapshots: [
        {
          id: "snap-2024",
          year: 2024,
          dateRecorded: "2024-12-31",
          totalNetWorth: -16500,
          totalLiquidSavings: 2500,
          totalInvestments: 1000,
          totalLiabilities: 20000,
          annualIncome: 12000,
          annualSavingsRate: 15,
          financialHealthScore: 42,
          keyMilestoneAchieved: "Graduated university & began repayment plan for student tuition loan.",
          reflectionNotes: "Started with limited cash and $20k in student loans.",
        },
        {
          id: "snap-2025",
          year: 2025,
          dateRecorded: "2025-12-31",
          totalNetWorth: 2800,
          totalLiquidSavings: 5200,
          totalInvestments: 4500,
          totalLiabilities: 18000,
          annualIncome: 45000,
          annualSavingsRate: 22,
          financialHealthScore: 65,
          keyMilestoneAchieved: "Turned Net Worth POSITIVE! Started auto-investing S$150/mo into Syfe & Endowus.",
          reflectionNotes: "Great consistency. Built 3 months of emergency fund.",
        },
        {
          id: "snap-2026",
          year: 2026,
          dateRecorded: "2026-08-15",
          totalNetWorth: 10700,
          totalLiquidSavings: 8500,
          totalInvestments: 9200,
          totalLiabilities: 16000,
          annualIncome: 50400,
          annualSavingsRate: 26,
          financialHealthScore: 78,
          keyMilestoneAchieved: "Completed 6-month safety stash & expanded DCA across global index ETFs!",
          reflectionNotes: "Strong progress. On track to be debt-free by age 28.",
        },
      ],
      dependents: [
        {
          id: "dep-mom",
          name: "Mother (Monthly Allowance)",
          relationship: "parent",
          age: 55,
          yearsOfSupportNeeded: 20,
          monthlySupportAmount: 400,
        },
      ],
      incomes: [
        { id: "inc-1", category: "employment", description: "Monthly Base Salary (Take-Home)", monthlyAmount: 3800 },
        { id: "inc-2", category: "other", description: "Side Gig / Freelancing", monthlyAmount: 400 },
      ],
      expenses: [
        { id: "exp-1", category: "housing", description: "Rent / Living Expenses", monthlyAmount: 900, isEssential: true },
        { id: "exp-2", category: "food", description: "Food, Groceries & Coffee", monthlyAmount: 700, isEssential: true },
        { id: "exp-3", category: "transport", description: "Public Transit & Commute", monthlyAmount: 180, isEssential: true },
        { id: "exp-4", category: "utilities", description: "Phone, Wi-Fi & Subscriptions", monthlyAmount: 120, isEssential: true },
        { id: "exp-5", category: "lifestyle", description: "Weekend Socializing & Hobbies", monthlyAmount: 450, isEssential: false },
      ],
      assets: [
        {
          id: "ast-1",
          category: "cash_savings",
          description: "High-Yield Bank Account",
          platformOrVehicle: "DBS Multiplier / UOB One",
          currentValue: 8500,
          isLiquid: true,
          expectedReturnRate: 3.2,
          monthlyContribution: 200,
          targetPurpose: "emergency",
        },
        {
          id: "ast-2",
          category: "stocks_funds",
          description: "Robo-Advisor Portfolio",
          platformOrVehicle: "Syfe Core Balanced / StashAway",
          currentValue: 4200,
          isLiquid: false,
          expectedReturnRate: 6.5,
          monthlyContribution: 100,
          targetPurpose: "wealth_growth",
        },
        {
          id: "ast-3",
          category: "stocks_funds",
          description: "Global Equities / S&P 500 ETF",
          platformOrVehicle: "Endowus / Interactive Brokers (CSPX)",
          currentValue: 5000,
          isLiquid: false,
          expectedReturnRate: 7.5,
          monthlyContribution: 150,
          targetPurpose: "retirement",
        },
        {
          id: "ast-4",
          category: "cpf_epf_pension",
          description: "Retirement / CPF Savings",
          platformOrVehicle: "CPF Ordinary & Special Account",
          currentValue: 9000,
          isLiquid: false,
          expectedReturnRate: 4.0,
          monthlyContribution: 0,
          targetPurpose: "retirement",
        },
      ],
      liabilities: [
        {
          id: "lia-1",
          category: "study_loan",
          description: "University Tuition Loan",
          outstandingBalance: 16000,
          monthlyRepayment: 350,
          interestRate: 2.5,
          tenureYearsRemaining: 4,
          originalAmount: 20000,
        },
      ],
      insurancePolicies: [
        {
          id: "pol-1",
          policyName: "Basic Hospital & Medical Shield",
          insurer: "AIA",
          policyType: "hospital_surgical",
          deathBenefit: 30000,
          tpdBenefit: 30000,
          earlyCiBenefit: 0,
          majorCiBenefit: 30000,
          disabilityIncomeMonthly: 0,
          annualPremium: 400,
          expiryAge: 99,
        },
        {
          id: "pol-2",
          policyName: "Retirement Annuity Plan",
          insurer: "Great Eastern / Manulife",
          policyType: "endowment",
          deathBenefit: 50000,
          tpdBenefit: 50000,
          earlyCiBenefit: 0,
          majorCiBenefit: 0,
          disabilityIncomeMonthly: 0,
          annualPremium: 1200,
          currentCashValue: 2400,
          projectedRetirementMaturityValue: 95000,
        },
      ],
      goals: [
        {
          id: "goal-wedding",
          name: "Wedding & Honeymoon Trip",
          category: "wedding",
          horizonBucket: "short_term",
          targetYearsFromNow: 2,
          targetAmount: 24000,
          currentSavingsAssigned: 6000,
          recommendedVehicle: "High-Yield Bank Cash (3.2%)",
        },
        {
          id: "goal-bto",
          name: "BTO Home Downpayment & Renovation",
          category: "property",
          horizonBucket: "mid_term",
          targetYearsFromNow: 4,
          targetAmount: 50000,
          currentSavingsAssigned: 10000,
          recommendedVehicle: "Balanced Robo-Advisor (4.5%)",
        },
        {
          id: "goal-retirement",
          name: "Financial Freedom (FIRE at 58)",
          category: "retirement",
          horizonBucket: "long_term",
          targetYearsFromNow: 34,
          targetAmount: 850000,
          currentSavingsAssigned: 9200,
          recommendedVehicle: "Global Equities / ETFs (7.0%)",
        },
      ],
      assumptions: {
        generalInflationRate: 3.0,
        medicalInflationRate: 8.0,
        educationInflationRate: 5.0,
        investmentReturnRate: 7.0,
        postRetirementReturnRate: 3.5,
        emergencyFundMonthsTarget: 6,
        familySupportYearsTarget: 10,
        ciIncomeReplacementYears: 4,
      },
    },
  },
  young_family: {
    label: "👨‍👩‍👧 Young Family with Mortgage (Age 32)",
    description: "Married with toddler, HDB mortgage, child education fund, and retirement at 62.",
    data: {
      id: "profile-young-family",
      name: "Jordan & Chloe",
      currentAge: 32,
      targetRetirementAge: 62,
      lifeExpectancy: 88,
      desiredMonthlyRetirementSpendToday: 4200,
      retirementLifestylePreset: "comfortable",
      maritalStatus: "married",
      employmentType: "employed",
      riskProfile: "balanced",
      currency: "SGD",
      cpfLife: {
        isEnabled: true,
        planTier: "full_frs",
        estimatedMonthlyPayoutToday: 1800,
        payoutStartAge: 65,
      },
      dependents: [
        {
          id: "dep-kid",
          name: "Emma (Toddler)",
          relationship: "child",
          age: 2,
          yearsOfSupportNeeded: 20,
          monthlySupportAmount: 800,
          tertiaryEducationTarget: 80000,
          yearsToTertiary: 16,
        },
      ],
      incomes: [
        { id: "inc-yf1", category: "employment", description: "Monthly Combined Salary", monthlyAmount: 7500 },
      ],
      expenses: [
        { id: "exp-yf1", category: "housing", description: "Home Mortgage Repayment", monthlyAmount: 2200, isEssential: true },
        { id: "exp-yf2", category: "food", description: "Groceries & Household Dining", monthlyAmount: 1100, isEssential: true },
        { id: "exp-yf3", category: "transport", description: "Family Transport & Commute", monthlyAmount: 400, isEssential: true },
        { id: "exp-yf4", category: "utilities", description: "Utilities, Bills & Subscriptions", monthlyAmount: 350, isEssential: true },
        { id: "exp-yf5", category: "lifestyle", description: "Baby Activities & Social", monthlyAmount: 650, isEssential: false },
      ],
      assets: [
        {
          id: "ast-yf1",
          category: "cash_savings",
          description: "Emergency Cash Stash",
          platformOrVehicle: "High-Yield Bank Account",
          currentValue: 30000,
          isLiquid: true,
          expectedReturnRate: 3.0,
          monthlyContribution: 300,
          targetPurpose: "emergency",
        },
        {
          id: "ast-yf2",
          category: "stocks_funds",
          description: "Robo-advisor (Endowus Core / Syfe)",
          platformOrVehicle: "Endowus Flagship Global",
          currentValue: 28000,
          isLiquid: false,
          expectedReturnRate: 6.5,
          monthlyContribution: 400,
          targetPurpose: "retirement",
        },
        {
          id: "ast-yf3",
          category: "stocks_funds",
          description: "Vanguard Total World ETF",
          platformOrVehicle: "Interactive Brokers (VWRA)",
          currentValue: 17000,
          isLiquid: false,
          expectedReturnRate: 7.0,
          monthlyContribution: 300,
          targetPurpose: "retirement",
        },
        {
          id: "ast-yf4",
          category: "cpf_epf_pension",
          description: "Retirement / CPF Balances",
          platformOrVehicle: "CPF Ordinary & Special Acct",
          currentValue: 90000,
          isLiquid: false,
          expectedReturnRate: 4.0,
          monthlyContribution: 0,
          targetPurpose: "retirement",
        },
      ],
      liabilities: [
        {
          id: "lia-yf1",
          category: "mortgage_primary",
          description: "HDB Housing Mortgage Loan",
          outstandingBalance: 460000,
          monthlyRepayment: 2000,
          interestRate: 2.6,
          tenureYearsRemaining: 23,
          originalAmount: 500000,
        },
        {
          id: "lia-yf2",
          category: "car_loan",
          description: "Car Hire Purchase Loan",
          outstandingBalance: 24000,
          monthlyRepayment: 550,
          interestRate: 2.78,
          tenureYearsRemaining: 4,
          originalAmount: 35000,
        },
      ],
      insurancePolicies: [
        {
          id: "pol-yf1",
          policyName: "Term Life Protection",
          insurer: "Great Eastern",
          policyType: "term_life",
          deathBenefit: 500000,
          tpdBenefit: 500000,
          earlyCiBenefit: 0,
          majorCiBenefit: 100000,
          disabilityIncomeMonthly: 0,
          annualPremium: 900,
          expiryAge: 65,
        },
      ],
      goals: [
        {
          id: "goal-yf-home-upgrade",
          name: "Home Reno & Enhancement",
          category: "renovation",
          horizonBucket: "short_term",
          targetYearsFromNow: 2,
          targetAmount: 20000,
          currentSavingsAssigned: 8000,
        },
        {
          id: "goal-yf-child-edu",
          name: "Emma's University College Fund",
          category: "education",
          horizonBucket: "long_term",
          targetYearsFromNow: 16,
          targetAmount: 90000,
          currentSavingsAssigned: 12000,
        },
        {
          id: "goal-yf-retire",
          name: "Retire Comfortably by 62",
          category: "retirement",
          horizonBucket: "long_term",
          targetYearsFromNow: 30,
          targetAmount: 1200000,
          currentSavingsAssigned: 45000,
        },
      ],
      assumptions: {
        generalInflationRate: 3.0,
        medicalInflationRate: 8.0,
        educationInflationRate: 5.0,
        investmentReturnRate: 6.5,
        postRetirementReturnRate: 3.5,
        emergencyFundMonthsTarget: 6,
        familySupportYearsTarget: 18,
        ciIncomeReplacementYears: 4,
      },
    },
  },
};

export const DEFAULT_BLANK_PROFILE: UserFinancialProfile = {
  id: "profile-new",
  name: "My Money Plan",
  currentAge: 24,
  targetRetirementAge: 60,
  lifeExpectancy: 88,
  desiredMonthlyRetirementSpendToday: 2800,
  retirementLifestylePreset: "comfortable",
  maritalStatus: "single",
  employmentType: "employed",
  riskProfile: "moderate",
  currency: "SGD",
  cpfLife: {
    isEnabled: true,
    planTier: "full_frs",
    estimatedMonthlyPayoutToday: 1650,
    payoutStartAge: 65,
  },
  dependents: [],
  incomes: [
    { id: "inc-def-1", category: "employment", description: "Primary Monthly Salary", monthlyAmount: 3800 },
  ],
  expenses: [
    { id: "exp-def-1", category: "housing", description: "Rent / Living Expenses", monthlyAmount: 900, isEssential: true },
    { id: "exp-def-2", category: "food", description: "Food & Groceries", monthlyAmount: 600, isEssential: true },
    { id: "exp-def-3", category: "transport", description: "Transport / Commute", monthlyAmount: 150, isEssential: true },
    { id: "exp-def-4", category: "utilities", description: "Phone & Subscriptions", monthlyAmount: 100, isEssential: true },
    { id: "exp-def-5", category: "lifestyle", description: "Social & Hobbies", monthlyAmount: 400, isEssential: false },
  ],
  assets: [
    {
      id: "ast-def-1",
      category: "cash_savings",
      description: "Bank Savings",
      platformOrVehicle: "High-Yield Bank Account",
      currentValue: 8000,
      isLiquid: true,
      expectedReturnRate: 2.8,
      monthlyContribution: 200,
      targetPurpose: "emergency",
    },
  ],
  liabilities: [],
  insurancePolicies: [],
  goals: [
    {
      id: "goal-def-1",
      name: "Financial Freedom by 60",
      category: "retirement",
      horizonBucket: "long_term",
      targetYearsFromNow: 36,
      targetAmount: 750000,
      currentSavingsAssigned: 2000,
    },
  ],
  assumptions: {
    generalInflationRate: 3.0,
    medicalInflationRate: 8.0,
    educationInflationRate: 5.0,
    investmentReturnRate: 6.5,
    postRetirementReturnRate: 3.5,
    emergencyFundMonthsTarget: 6,
    familySupportYearsTarget: 10,
    ciIncomeReplacementYears: 4,
  },
};
